services:
  api-service:
    build:
      context: .
    ports:
      - 5000:8080
    networks:
      - backend

    depends_on:
      - job-queue
  job-queue:
    image: redis:latest
    environment:
      - REDIS_USER=reduser
      - REDIS_USER_PASSWORD=12345
    ports:
      - 5001:6379
    networks:
      - backend

networks:
  backend: